### ISSUE TITLE
I don't  kown  how to set ignore_errors

### ISSUE THREAD

**Issue by ArcherZkd** [fbzhong/sublime-jslint#14]
hallo:
     Thanks for  you  make  the  jslint and closuer - lint on ST2,it' very  great thing, but  i  found  some  problems and  my  English  bad,
    " ignore_errors" need regex?  can you give  me  a  example   I don't  how  to  do  5555~
    When  i  try   closuer - lint   i  found  The  file  can't  be  decode,the file code  is "utf-8"

Traceback (most recent call last):
  File ".\gjslint.py", line 64, in append_data
  File ".\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: invalid data

I don't kown  it  eighter!  need  help!

**Comment by ghost** [comment]
Please do not post bug reports about the Closure Linter ST plugin here, this is for JSLint plugin-related issues only. Also, this issue has already been reported (https://github.com/fbzhong/sublime-closure-linter/issues/3).
