### ISSUE TITLE
Highlight colour setting

### ISSUE THREAD

**Issue by johandam** [fbzhong/sublime-jslint#20]
The default highlighter is very ugly in my color scheme but I do not see a way to modify this, is it available or could it be implemented?

**Comment by ghost** [comment]
Could you expand, please? Is the highlight colour different in your colour scheme to the highlight colour in the default colour scheme, or do you simply dislike the highlight colour?

**Comment by ghost** [comment]
Closing this as the issue thread is seemingly dead, with no response in over a month. Granted, the issue was created well over two years ago.
