### ISSUE TITLE
Feature request: Lint only js scopes

### ISSUE THREAD

**Issue by pwntester** [fbzhong/sublime-jslint#26]
Hi, 
Would it be possible to lint only the js scopes instead of the whole document?
Think about HTML pages with <script> blocks or like my case, a XML file where some js can be included.

Thanks,
A.

**Comment by ghost** [comment]
Actually, looking at this it appears to be that this was removed in JSLint version 2013-05-01 (and JSLint4Java version 2.0,4), so to remedy this just download the 2.0.3 version of JSLint4Java from https://code.google.com/p/jslint4java/ and replace the 2.0.5 executable incuded by default with sublime-jslint.

**Comment by ghost** [comment]
I may add this into sublime-jslint in the future, but for now the executable swap should suffice.
